apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
    region: IN
    app.kubernetes.io/managed-by: Helm
  name: prometheus-service
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
    nodePort: {{ .Values.myservice.port }}
  selector:
    app: prometheus
    region: IN
  type: {{ .Values.myservice.type }}
status:
  loadBalancer: {}